# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HCFWY0KaBfdyXAdiNmSv9LJ8J66jictJ
"""

class Pessoas:
 def __init__(self, nome_completo, genero, idade):
   self.nome_completo = nome_completo
   self.genero = genero
   self.idade = idade

maria = Pessoas('Maria dos Santos', 'Feminino', '22 anos')
print( "Nome: " + maria.nome_completo + "\n" + "Genero: " + maria.genero + "\n" +"Idade:" + maria.idade)

class Estudantes:
 def __init__(self, nome_completo, matricula, curso):
   self.nome_completo = nome_completo
   self.matricula = matricula
   self.curso = curso

maria = Estudantes('Maria dos Santos', '2022013265', 'Psicologia')
print( "Nome: " +maria.nome_completo + "\n" + "Matricula: " + maria.matricula + "\n" + "Curso: " + maria.curso)

class Professores:
 def __init__(self, nome_completo, matricula, curso):
   self.nome_completo = nome_completo
   self.matricula = matricula
   self.curso = curso

maria = Professores('Maria dos Santos professora', '0000001', 'Turismo')
print( "Nome: " +maria.nome_completo + "\n" + "Matricula: " + maria.matricula + "\n" + "Curso: " + maria.curso)